name: base
channels:
  - conda-forge
  - bioconda
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - libgcc=7.2
  - setuptools=59.5.0
  - pip
  - openmm=7.7
  - pdbfixer
  - cudatoolkit==11.6.*
  - pytorch-lightning==1.8.4
  - biopython==1.79
  - numpy==1.21
  - PyYAML==5.4.1
  - requests
  - catboost
  - tqdm==4.62.2
  - typing-extensions==4.10
  - modelcif==0.7
  - awscli
  - ml-collections
  - aria2 
  - git
  - bioconda::hmmer==3.3.2
  - bioconda::hhsuite==3.3.0
  - bioconda::kalign2==2.04
  - pytorch::pytorch==1.13.*
  - pip:
      - triton==2.2.0
      - deepspeed==0.12.4
      - dm-tree==0.1.6
      - pandas==2.0.0
      - scikit-learn==1.4.*
      - scipy==1.11.4
      - pygad==3.3.1
      - biopandas
      - biopython
      - transformers
      - git+https://github.com/NVIDIA/dllogger.git
      - git+https://github.com/Dao-AILab/flash-attention.git@5b838a8
      
